version: "2"

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus:ro
    ports:
      - "9090:9090"
    labels:
      # tell the rc_cube that all ports mapped to the host (rc_cube) are using http
      - com.roboception.app.http
    extra_hosts:
      - "rc-cube.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    ports:
      - "8080:3000"
    labels:
      # alternate way to specify the protocol: for a specific port only
      - com.roboception.app.http.port=8080
    restart: unless-stopped
