version: "2"

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - "9091:9090"
    extra_hosts:
      - "rc-cube.internal:host-gateway"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:8.2.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "9092:3000"
    restart: unless-stopped
