version: "2.4"

volumes:
    prometheus_data:
      driver: local
    prometheus_etc:
      driver: local
    grafana_data:
      driver: local

services:
  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus:/etc/prometheus
    ports:
      - "9091:9090"
    extra_hosts:
      - "rc_cube.internal:host-gateway"

  grafana:
    image: grafana/grafana:8.2.1
    container_name: grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "9092:3000"

