{
 "title": "rc_cube",
 "description": "Dashboard to get an overview of the rc_cube",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pipeline",
    "query": {
     "query": "label_values(node_rc_camera_tl_ready{instance=~\"rc-cube.internal.*\"}, pipeline)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"rc-cube.internal.*\"} / (node_memory_MemTotal_bytes{instance=~\"rc-cube.internal.*\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"rc-cube.internal.*\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {instance=~\"rc-cube.internal.*\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount($maxmount)"
    },
    {
     "expr": "(1 - (node_memory_SwapFree_bytes{instance=~\"rc-cube.internal.*\"} / node_memory_SwapTotal_bytes{instance=~\"rc-cube.internal.*\"})) * 100",
     "legendFormat": "Used SWAP"
    }
   ]
  },
  {
   "title": "containers",
   "type": "stat",
   "description": "Running UserSpace containers",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{instance=~\"rc-cube.internal.*\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"rc-cube.internal.*\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance=~\"rc-cube.internal.*\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~\"rc-cube.internal.*\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{instance=~\"rc-cube.internal.*\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  { "title": "camera $pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "pipeline" },
  {
   "title": "GEV packet size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_tl_gev_packet_size{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "complete_bufers/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_rc_camera_tl_complete_buffers_total{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}[30s])"
    }
   ]
  },
  {
   "title": "image receive timeouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_tl_image_receive_timeouts_total{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "incomplete buffers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_tl_incomplete_buffers_total{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "connection losses",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_tl_connection_loss_total{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "image latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_tl_image_latency{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "Camera FPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_fps{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "Camera exposure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_exp{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "Camera gain",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_gain{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "Stereo FPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_stereomatching_fps{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "Max Stereo latency",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "node_rc_stereomatching_latency{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  {
   "title": "Out1 reduction",
   "type": "stat",
   "description": "Fraction of reduction (0.0 - 1.0) of exposure time for images with GPIO Out1=Low vs Out1=High",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_camera_out1_reduction{instance=~\"rc-cube.internal.*\",pipeline=\"$pipeline\"}"
    }
   ]
  },
  { "title": "GEV external", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GEV packet size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_gev_server_packet_size{instance=~\"rc-cube.internal.*\"}"
    }
   ]
  },
  {
   "title": "GEV streaming",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_gev_server_streaming{instance=~\"rc-cube.internal.*\"}"
    }
   ]
  },
  {
   "title": "GEV packet resends",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_gev_server_packet_resends_total{instance=~\"rc-cube.internal.*\"}"
    }
   ]
  },
  {
   "title": "GEV sent_frames/s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_rc_gev_server_sent_frames_total{instance=~\"rc-cube.internal.*\"}[30s])"
    }
   ]
  },
  {
   "title": "GEV dropped_frames",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_rc_gev_server_dropped_frames_total{instance=~\"rc-cube.internal.*\"}"
    }
   ]
  },
  { "title": "Resource usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "system"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "user"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"rc-cube.internal.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"idle\"})",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"rc-cube.internal.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"idle\"})",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"rc-cube.internal.*\"} / count without(cpu, mode) (node_cpu_seconds_total{instance=~\"rc-cube.internal.*\",mode=\"idle\"})",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"rc-cube.internal.*\"} - node_memory_MemAvailable_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "avaliable"
    },
    {
     "expr": "node_memory_Active_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "active"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "CPU usage per core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (irate(node_cpu_seconds_total{mode=\"idle\", instance=~\"rc-cube.internal.*\"}[5m])) * 100)",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"rc-cube.internal.*\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"rc-cube.internal.*\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "TCP_alloc"
    }
   ]
  },
  {
   "title": "CPU pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_pressure_cpu_waiting_seconds_total{instance=~\"rc-cube.internal.*\"}[$__rate_interval])",
     "legendFormat": "waiting"
    }
   ]
  },
  {
   "title": "IO pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{instance=~\"rc-cube.internal.*\"}[$__rate_interval])",
     "legendFormat": "waiting"
    },
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{instance=~\"rc-cube.internal.*\"}[$__rate_interval])",
     "legendFormat": "stalled"
    }
   ]
  },
  {
   "title": "Memory pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_pressure_memory_waiting_seconds_total{instance=~\"rc-cube.internal.*\"}[$__rate_interval])",
     "legendFormat": "waiting"
    },
    {
     "expr": "rate(node_pressure_memory_stalled_seconds_total{instance=~\"rc-cube.internal.*\"}[$__rate_interval])",
     "legendFormat": "stalled"
    }
   ]
  },
  { "title": "UserSpace containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_usage_seconds_total{instance=~\"rc-cube.internal.*\",image!=\"\"}[1m])) by (name))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=~\"rc-cube.internal.*\",image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{instance=~\"rc-cube.internal.*\",image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }} rx"
    },
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{instance=~\"rc-cube.internal.*\",image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }} tx"
    }
   ]
  },
  {
   "title": "Container network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{instance=~\"rc-cube.internal.*\",image!=\"\"}[5m])) by (name)",
     "legendFormat": "{{ name }} write"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{instance=~\"rc-cube.internal.*\",image!=\"\"}[5m])) by (name)",
     "legendFormat": "{{ name }} read"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "# GPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_gpu_num_devices{instance=~\"rc-cube.internal.*\"}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{instance=~\"rc-cube.internal.*\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_gpu_memory_used_bytes{instance=~\"rc-cube.internal.*\"}) / (sum(nvidia_gpu_memory_total_bytes{instance=~\"rc-cube.internal.*\"}))"
    }
   ]
  },
  {
   "title": "GPU Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "Memory Utilization / Card",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 73 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_memory_used_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "gpu{{minor_number}}"
    },
    {
     "expr": "nvidia_gpu_memory_total_bytes{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "gpu{{minor_number}} total"
    }
   ]
  },
  {
   "title": "Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nvidia_gpu_duty_cycle{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_power_usage_milliwatts{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 79 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_temperature_celsius{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 79 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "nvidia_gpu_fanspeed_percent{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "gpu{{minor_number}}"
    }
   ]
  },
  { "title": "misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "short", "label": "deg celcius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "{{chip}} {{sensor}}"
    },
    {
     "expr": "node_rc_camera_temp_left{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "cam_left"
    },
    {
     "expr": "node_rc_camera_temp_right{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "cam_right"
    }
   ]
  },
  {
   "title": "CPU scaling frequency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=~\"rc-cube.internal.*\"}",
     "legendFormat": "cpu{{cpu}}"
    }
   ]
  }
 ]
}